'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {setup,collectionReceipt}=require('./collection_editor_fixture.cjs');
const source=path.join(__dirname,'../app/static/collection-editor.js');
const A='a'.repeat(32),B='b'.repeat(32),W='1'.repeat(32);
function page(){
  const s=setup({autoOpen:false});
  s.run(`post=(url,data)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
    assetState.collections=[{id:'${A}',name:'Portraits',description:'Keep this description',count:2,revision:1},{id:'${B}',name:'Other',description:'Other notes',count:0,revision:1}];assetScope='all';assetSelection=new Set(['a']);`);
  if(fs.existsSync(source))s.run(fs.readFileSync(source,'utf8'));
  const submit=()=>s.el('#collectionForm').onsubmit({preventDefault(){}});
  const resolve=(index=0)=>{const p=s.payload(index);s.writes[index].resolve(collectionReceipt(p,A));};
  return {...s,submit,resolve,open:id=>s.run(`openCollection(${id?JSON.stringify(id):''})`)};
}
let passed=0,failed=0;
async function test(name,fn){try{await fn();passed++;console.log('PASS',name);}catch(e){failed++;console.error('FAIL',name,e.message);}}
(async()=>{
 await test('Missing target preserves the existing draft',async()=>{const s=page();s.open(A);s.el('#collectionName').value='Draft';s.open('missing');assert.equal(s.el('#collectionName').value,'Draft');});
 await test('Cancel and Escape both ask before discarding',async()=>{const s=page();s.open();s.el('#collectionName').value='Draft';s.el('#cancelCollection').onclick();assert.equal(s.el('#collectionDialog').open,true);let prevented=false;s.el('#collectionDialog').emit('cancel',{preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(s.el('#collectionDialog').open,true);assert.equal(s.confirmations(),2);});
 await test('Opening the same editor is inert; another respects Stay',async()=>{const s=page();s.open(A);s.el('#collectionName').value='Draft';s.open(A);assert.equal(s.el('#collectionName').value,'Draft');s.open(B);assert.equal(s.el('#collectionName').value,'Draft');});
 await test('Blank and oversized fields refuse before dispatch',async()=>{const s=page();s.open();s.el('#collectionName').value='   ';const p=s.submit();if(s.writes.length)s.resolve();await p;s.el('#collectionName').value='x'.repeat(101);const q=s.submit();if(s.writes.length>1)s.resolve(1);await q;assert.equal(s.writes.length,0);assert.match(s.el('#collectionStatus').textContent,/100|name/i);});
 await test('One click-time snapshot; duplicate and leave are held',async()=>{const s=page();s.open();s.el('#collectionName').value='New';const p=s.submit();void s.submit();assert.equal(s.writes.length,1);assert.equal(s.el('#saveCollection').disabled,true);s.el('#cancelCollection').onclick();assert.equal(s.el('#collectionDialog').open,true);s.el('#collectionDescription').value='Newer';s.resolve();await p;assert.equal(s.el('#collectionDescription').value,'Newer');assert.match(s.el('#collectionStatus').textContent,/unsaved/);});
 await test('Confirmed Create becomes Edit without closing or changing selection',async()=>{const s=page();s.open();s.el('#collectionName').value='New';const p=s.submit();s.resolve();await p;assert.equal(s.el('#collectionDialog').open,true);assert.equal(s.run('assetScope'),'all');assert.equal(s.run('assetSelection.has("a")'),true);s.el('#collectionName').value='Renamed';const p2=s.submit();assert.equal(s.payload(1).action,'rename');assert.equal(s.payload(1).id,A);s.resolve(1);await p2;});
 await test('Unchanged edit submits nothing',async()=>{const s=page();s.open(A);const p=s.submit();if(s.writes.length)s.resolve();await p;assert.equal(s.writes.length,0);});
 await test('Validation failure is visible and retains the draft',async()=>{const s=page();s.open(A);s.el('#collectionName').value='Edited';const p=s.submit();const e=Error('Name rejected');e.status=400;s.writes[0].reject(e);await p;assert.equal(s.el('#collectionName').value,'Edited');assert.match(s.el('#collectionStatus').textContent,/Name rejected/);assert.equal(s.el('#saveCollection').disabled,false);});
 await test('Lost response holds further saves instead of blindly retrying',async()=>{const s=page();s.open();s.el('#collectionName').value='New';const p=s.submit();s.writes[0].reject(Error('connection lost'));await p;assert.match(s.el('#collectionStatus').textContent,/not confirmed/);assert.equal(s.el('#saveCollection').disabled,true);void s.submit();assert.equal(s.writes.length,1);s.el('#cancelCollection').onclick();assert.equal(s.el('#collectionDialog').open,true);});
 await test('Deadline aborts and no late success changes the panel',async()=>{const s=page();s.open();s.el('#collectionName').value='New';const p=s.submit();[...s.timers.values()][0]();await p;assert.equal(s.writes[0].options.signal.aborted,true);assert.match(s.el('#collectionStatus').textContent,/not confirmed/);assert.equal(s.el('#collectionDialog').open,true);assert.equal(s.timers.size,0);});
 await test('Malformed successful response remains unconfirmed',async()=>{const s=page();s.open();s.el('#collectionName').value='New';const p=s.submit();s.writes[0].resolve({});await p;assert.match(s.el('#collectionStatus').textContent,/not confirmed/);assert.equal(s.el('#saveCollection').disabled,true);});
 await test('Scope change refuses before a write',async()=>{const s=page();s.open(A);s.el('#collectionName').value='Edited';s.run("assetState.workspace_id='2'.repeat(32)");const p=s.submit();if(s.writes.length)s.resolve();await p;assert.equal(s.writes.length,0);assert.match(s.el('#collectionStatus').textContent,/Workspace/);});
 await test('Commands carry the opened Workspace identity',async()=>{const s=page();s.open(A);s.el('#collectionName').value='Edited';const p=s.submit();assert.equal(s.payload(0).workspace_id,W);assert.equal(s.payload(0).format,'studio.collection-command/v1');assert.equal(s.payload(0).expected_revision,1);assert.match(s.payload(0).request_id,/^[A-Za-z0-9_-]{16,128}$/);s.resolve();await p;});
 await test('Delete cancellation sends no command and preserves selection',async()=>{const s=page();s.run(`assetScope='collection:${A}'`);const p=s.el('#deleteCollection').onclick();if(s.writes.length)s.resolve();await p;assert.equal(s.writes.length,0);assert.equal(s.run('assetSelection.has("a")'),true);assert.equal(s.confirmations(),1);});
 await test('Delete failure stays with its captured collection',async()=>{const s=page();s.approve(true);s.run(`assetScope='collection:${A}'`);const p=s.el('#deleteCollection').onclick();s.writes[0].reject(Error('connection lost'));await p;assert.equal(s.el('#collectionDialog').open,true);assert.match(s.el('#collectionStatus').textContent,/not confirmed/);assert.equal(s.run('assetScope'),`collection:${A}`);});
 await test('A stale callback cannot close a replacement dialog',async()=>{const s=page();s.open(A);s.el('#collectionName').value='Edited';const p=s.submit();s.el('#collectionDialog').close();s.open(B);s.resolve();await p;assert.equal(s.el('#collectionDialog').open,true);assert.equal(s.el('#collectionName').value,'Other');});
 console.log(JSON.stringify({passed,failed}));if(failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
