'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const file=path.join(__dirname,'../app/static/collection-recovery.js');
assert.ok(fs.existsSync(file),'collection recovery must retain exact commands across reload');
const R=require(file),W='1'.repeat(32),V='2'.repeat(32),A='a'.repeat(32),B='b'.repeat(32);
const {collectionReceipt}=require('./collection_editor_fixture.cjs');
function storage(){const data=new Map();return {data,get length(){return data.size;},key:i=>[...data.keys()][i]??null,getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
function draft(id=null,revision=null,name='Draft'){return {id,revision,baseline:{name:id?'Before':'',description:''},values:{name,description:'Notes'},updated_at:123};}
function command(id=null){return {format:'studio.collection-command/v1',workspace_id:W,request_id:'recovery-request-0001',action:id?'rename':'create',...(id?{id,expected_revision:1}:{}),name:'Clicked',description:'Earlier'};}
let passed=0;
async function test(name,fn){await fn();passed++;console.log('PASS',name);}
(async()=>{
 await test('empty inspection is read only',()=>{const s=storage(),j=new R.Journal(s,W);assert.deepEqual(j.list(),[]);assert.equal(j.get(null),null);assert.equal(s.length,0);});
 await test('create and rename drafts survive a new journal instance',()=>{const s=storage(),j=new R.Journal(s,W);j.keep(draft());j.keep(draft(A,1));const reopened=new R.Journal(s,W);assert.deepEqual(reopened.get(null).draft,draft());assert.deepEqual(reopened.get(A).draft,draft(A,1));});
 await test('newer typing cannot rewrite or drop an immutable pending command',()=>{const s=storage(),j=new R.Journal(s,W),p=R.pending(command(),123);j.keep(draft(),p);j.keep(draft(null,null,'Newer'),p);assert.equal(j.get(null).pending.body,p.body);const before=s.getItem(j.key);assert.throws(()=>j.keep(draft(),null),/pending|unconfirmed/i);assert.throws(()=>j.keep(draft(),R.pending({...command(),name:'Changed'},123)),/pending|unconfirmed/i);assert.equal(s.getItem(j.key),before);});
 await test('exact command bytes and duplicated identity are validated',()=>{const s=storage(),j=new R.Journal(s,W),p=R.pending(command(),123);assert.equal(p.body,R.canonical(command()));for(const altered of [{...p,body:' '+p.body},{...p,request_id:'different-request-1'},{...p,action:'delete'},{...p,target_id:A},{...p,expected_revision:1}])assert.throws(()=>j.keep(draft(),altered));assert.equal(s.length,0);});
 await test('pending scope and source revision must match its draft',()=>{const s=storage(),j=new R.Journal(s,W);assert.throws(()=>j.keep(draft(),R.pending({...command(),workspace_id:V},123)));assert.throws(()=>j.keep(draft(A,2),R.pending(command(A),123)));assert.equal(s.length,0);});
 await test('definite settlement removes exactly the old command and preserves newer text',()=>{const s=storage(),j=new R.Journal(s,W),p=R.pending(command(),123);j.keep(draft(),p);j.keep(draft(B,1,'Unrelated'));const next={...draft(A,1,'Newer'),baseline:{name:'Clicked',description:'Earlier'}};j.resolve(null,p,next);assert.equal(j.get(null),null);assert.deepEqual(j.get(A).draft,next);assert.equal(j.get(A).pending,null);assert.equal(j.get(B).draft.values.name,'Unrelated');});
 await test('settlement cannot overwrite another recovered target',()=>{const s=storage(),j=new R.Journal(s,W),p=R.pending(command(),123);j.keep(draft(),p);j.keep(draft(A,1));const before=s.getItem(j.key);assert.throws(()=>j.resolve(null,p,draft(A,1)),/existing|another/i);assert.equal(s.getItem(j.key),before);});
 await test('settlement checks the entire retained pending identity',()=>{const s=storage(),j=new R.Journal(s,W),p=R.pending(command(),123);j.keep(draft(),p);assert.throws(()=>j.resolve(null,{...p,first_dispatch_at:124},draft(A,1)));assert.equal(j.get(null).pending.body,p.body);});
 await test('other tabs and replaced Workspaces cannot adopt recovery',()=>{const s=storage(),j=new R.Journal(s,W);j.keep(draft());assert.deepEqual(new R.Journal(s,V).list(),[]);assert.deepEqual(new R.Journal(storage(),W).list(),[]);const copy=storage();copy.setItem(j.key,s.getItem(j.key));assert.deepEqual(new R.Journal(copy,W).get(null),j.get(null));new R.Journal(copy,W).discard(null);assert.ok(j.get(null));});
 await test('quota, disabled storage, and changed readback fail closed',()=>{const bad={getItem(){throw Error('disabled');}};assert.throws(()=>new R.Journal(bad,W).list(),/disabled/);for(const mode of ['quota','changed']){const s=storage(),j=new R.Journal(s,W);s.setItem=(k,v)=>{if(mode==='quota')throw Error('quota');s.data.set(k,v+' ');};assert.throws(()=>j.keep(draft()),/quota|verified|changed/i);}});
 await test('malformed, wrong-version, duplicate-key and oversized envelopes are never repaired',()=>{for(const raw of ['{','{"format":"old"}','{"format":"x","format":"x"}',' '.repeat(R.MAX_BYTES+1)]){const s=storage(),j=new R.Journal(s,W);s.setItem(j.key,raw);assert.throws(()=>j.get(null));assert.throws(()=>j.keep(draft()));assert.equal(s.getItem(j.key),raw);}});
 await test('invalid fields and UTF-16 lone surrogates refuse without truncation',()=>{const s=storage(),j=new R.Journal(s,W);for(const d of [{...draft(),values:{name:'x'.repeat(101),description:''}},{...draft(),values:{name:'x',description:'y'.repeat(1001)}},{...draft(),values:{name:'\ud800',description:''}},draft(A,0),draft(A,Number.MAX_SAFE_INTEGER+1),{...draft(),updated_at:-1}])assert.throws(()=>j.keep(d));assert.equal(s.length,0);});
 await test('count and global byte bounds refuse without evicting unresolved commands',()=>{const s=storage(),j=new R.Journal(s,W),p=R.pending(command(),123);j.keep(draft(),p);for(let i=1;i<R.MAX_ENTRIES;i++)j.keep(draft('item-'+i,1));const before=s.getItem(j.key);assert.throws(()=>j.keep(draft('extra',1)),/full|limit/i);assert.equal(s.getItem(j.key),before);s.setItem(R.PREFIX+V,'x'.repeat(R.MAX_BYTES));assert.throws(()=>j.keep(draft(),p),/full|limit/i);assert.equal(s.getItem(j.key),before);});
 await test('discards only the selected local target or explicitly the current Workspace',()=>{const s=storage(),j=new R.Journal(s,W),other=new R.Journal(s,V);j.keep(draft());j.keep(draft(A,1));other.keep(draft());j.discard(null);assert.equal(j.get(null),null);assert.ok(j.get(A));j.reset();assert.equal(s.getItem(j.key),null);assert.ok(other.get(null));});
 await test('hash-bound historical receipt is independent of current metadata',async()=>{const p=R.pending(command(),123),r=collectionReceipt(command(),A);r.current={id:A,name:'Another editor',description:'Later',revision:5};const verified=await R.verifyReceipt(r,p,crypto.webcrypto);assert.equal(verified.result.name,'Clicked');assert.equal(verified.result.revision,1);});
 await test('rehashed mismatching request, tampered bytes and duplicate receipt keys refuse',async()=>{const p=R.pending(command(),123);for(const change of [r=>{r.receipt.result.name='Injected';},r=>{r.receipt_sha256='0'.repeat(64);},r=>{r.receipt_json=r.receipt_json.replace('{','{"status":"committed",');r.receipt_sha256=crypto.createHash('sha256').update(r.receipt_json).digest('hex');},r=>{r.receipt.request_sha256='0'.repeat(64);r.receipt_json=R.canonical(r.receipt);r.receipt_sha256=crypto.createHash('sha256').update(r.receipt_json).digest('hex');}]){const r=collectionReceipt(command(),A);change(r);await assert.rejects(()=>R.verifyReceipt(r,p,crypto.webcrypto));}});
 await test('unknown, foreign, malformed and noncommitted replies are not confirmations',async()=>{const p=R.pending(command(),123);for(const change of [r=>{r.status='unknown';},r=>{r.workspace_id=V;},r=>{r.request_id='changed';},r=>{r.receipt.result.revision=2;},r=>{r.generation_submitted=true;}]){const r=collectionReceipt(command(),A);change(r);await assert.rejects(()=>R.verifyReceipt(r,p,crypto.webcrypto));}});
 await test('non-ASCII command identity matches Python canonical UTF-8 bytes',async()=>{const c={...command(),name:'Café 🐈',description:'Line\n two'},p=R.pending(c,123),r=collectionReceipt(c,A);await R.verifyReceipt(r,p,crypto.webcrypto);assert.equal(r.receipt.request_sha256,crypto.createHash('sha256').update(p.body).digest('hex'));});

 await test('discard remains possible when another Workspace exhausts the budget',()=>{const s=storage(),j=new R.Journal(s,W);j.keep(draft());j.keep(draft(A,1));s.setItem(R.PREFIX+V,'x'.repeat(R.MAX_BYTES));j.discard(null);assert.ok(j.get(A));j.discard(A);assert.equal(s.getItem(j.key),null);assert.equal(s.getItem(R.PREFIX+V).length,R.MAX_BYTES);});
 await test('an empty settled journal does not consume a Workspace slot',()=>{const s=storage(),j=new R.Journal(s,W),p=R.pending(command(),123);j.keep(draft(),p);j.resolve(null,p,null);assert.equal(s.length,0);});
 await test('clicked raw text is immutable metadata separate from normalized wire bytes',()=>{const c=command(),p=R.pending(c,123,{name:' Clicked ',description:'Earlier'});assert.equal(p.clicked_values.name,' Clicked ');assert.equal(p.body,R.canonical(c));assert.throws(()=>R.pending(c,123,{name:'Another',description:'Earlier'}));const s=storage(),j=new R.Journal(s,W);j.keep(draft(),p);assert.throws(()=>j.keep(draft(),{...p,clicked_values:{name:'Clicked',description:'Earlier'}}),/pending|unconfirmed/i);});
 console.log(JSON.stringify({passed}));
})().catch(e=>{console.error(e);process.exitCode=1;});
