'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {setup,collectionReceipt,memoryStorage}=require('./collection_editor_fixture.cjs');
const source=fs.readFileSync(path.join(__dirname,'../app/static/collection-editor.js'),'utf8'),W='1'.repeat(32),A='a'.repeat(32),B='b'.repeat(32);
function page(storage=memoryStorage()){
 const s=setup({storage});s.run(`assetState.collections=[{id:'${A}',name:'Before',description:'Original',revision:1},{id:'${B}',name:'Second',description:'',revision:1}];`);s.run(source);
 return {...s,open:(id=null)=>s.run(`openCollection(${JSON.stringify(id)})`),input:(id,text)=>{s.el(id).value=text;s.el(id).emit('input');},submit:()=>s.el('#collectionForm').onsubmit({preventDefault(){}}),restore:()=>s.el('#restoreCollectionDraft').onclick(),inspect:()=>s.el('#inspectCollectionCommand').onclick(),retry:()=>s.el('#retryCollectionCommand').onclick()};
}
let passed=0;
async function test(name,fn){await fn();passed++;console.log('PASS',name);}
(async()=>{
 await test('drafts are offered after reload, never automatically submitted or restored',()=>{const s=page();s.open();s.input('#collectionName','Local create');s.input('#collectionDescription','Retained');const r=page(s.storage);r.open();assert.equal(r.el('#restoreCollectionDraft').hidden,false,'reload must offer Restore');assert.equal(r.el('#saveCollection').disabled,true);r.restore();assert.equal(r.el('#collectionName').value,'Local create');assert.equal(r.el('#collectionDescription').value,'Retained');assert.equal(r.writes.length,0);assert.equal(r.reads.length,0);});
 await test('a rename draft retains its opened baseline and revision',()=>{const s=page();s.open(A);s.input('#collectionName','My rename');const r=page(s.storage);r.run(`assetState.collections[0].name='Other tab';assetState.collections[0].revision=2;`);r.open(A);r.restore();assert.equal(r.run('collectionSession.revision'),1);assert.equal(r.el('#collectionName').value,'My rename');assert.match(r.el('#collectionComparison').textContent,/Other tab/);assert.equal(r.writes.length,0);});
 await test('pending is durable before POST and newer typing does not alter its body',async()=>{const s=page();s.open();s.input('#collectionName','Clicked');const waiting=s.submit();assert.equal(s.writes.length,1);const body=s.writes[0].options.body;s.input('#collectionName','Newer');const stored=s.run('collectionSession.journal.get(null)');assert.equal(stored.pending.body,body);assert.equal(stored.draft.values.name,'Newer');s.writes[0].reject(Error('lost'));await waiting;const r=page(s.storage);r.open();r.restore();assert.equal(r.el('#collectionName').value,'Newer');assert.equal(r.el('#saveCollection').disabled,true);assert.equal(r.run('collectionSession.pending.body'),body);});
 await test('committed response loss reloads into read-only status and separates newer current metadata',async()=>{const s=page();s.open();s.input('#collectionName','Clicked');const waiting=s.submit(),payload=s.payload(0);s.writes[0].reject(Error('lost'));await waiting;const r=page(s.storage);r.open();r.restore();const inspect=r.inspect();assert.equal(r.writes.length,0);assert.equal(r.reads.length,1);assert.match(r.reads[0].url,new RegExp(payload.request_id));const reply=collectionReceipt(payload,A);reply.current={id:A,name:'Other tab later',description:'Current',revision:3};r.reads[0].resolve(reply);await inspect;assert.equal(r.run('collectionSession.pending'),null);assert.equal(r.run('collectionSession.revision'),1);assert.equal(r.el('#collectionName').value,'Clicked');assert.match(r.el('#collectionComparison').textContent,/Other tab later/);assert.match(r.el('#collectionComparison').textContent,/Historical/);assert.equal(r.writes.length,0);});
 await test('unknown status holds the command; explicit retry sends the identical body once',async()=>{const s=page();s.open();s.input('#collectionName','Clicked');const waiting=s.submit();s.writes[0].reject(Error('lost'));await waiting;const body=s.writes[0].options.body,payload=s.payload(0),r=page(s.storage);r.open();r.restore();const inspect=r.inspect();r.reads[0].resolve({format:'studio.collection-result/v1',workspace_id:W,request_id:payload.request_id,status:'unknown',receipt:null,receipt_json:null,receipt_sha256:null,generation_submitted:false});await inspect;assert.equal(r.el('#saveCollection').disabled,true);r.approve(true);const retry=r.retry();void r.retry();assert.equal(r.writes.length,1);assert.equal(r.writes[0].options.body,body);r.writes[0].resolve(collectionReceipt(payload,A));await retry;assert.equal(r.run('collectionSession.id'),A);});
 await test('explicit precommit refusal settles ambiguity but preserves editing',async()=>{const s=page();s.open(A);s.input('#collectionName','Kept');const waiting=s.submit(),error=Error('Invalid name');error.status=400;error.data={format:'studio.collection-error/v1',code:'collection_invalid_command',generation_submitted:false};s.writes[0].reject(error);await waiting;assert.equal(s.run('collectionSession.pending'),null);assert.equal(s.el('#collectionName').value,'Kept');assert.equal(s.el('#collectionName').disabled,false);assert.equal(s.el('#saveCollection').disabled,false);assert.equal(s.run(`collectionSession.journal.get('${A}').pending`),null);});
 await test('request-ID conflict and unstructured errors do not discard pending evidence',async()=>{for(const code of ['collection_request_conflict',null]){const s=page();s.open();s.input('#collectionName','Kept');const waiting=s.submit(),error=Error('Untrusted refusal');error.status=409;if(code)error.data={format:'studio.collection-error/v1',code,generation_submitted:false};s.writes[0].reject(error);await waiting;assert.ok(s.run('collectionSession.pending'));assert.equal(s.el('#saveCollection').disabled,true);}});
 await test('quota and changed writeback send zero writes and preserve visible input',async()=>{for(const mode of ['quota','changed']){const s=page();s.open();s.storage.setItem=(k,v)=>{if(mode==='quota')throw Error('quota');s.storage.data.set(k,v+' ');};s.input('#collectionName','Do not lose');await s.submit();assert.equal(s.writes.length,0);assert.equal(s.el('#collectionName').value,'Do not lose');assert.match(s.el('#collectionStatus').textContent,/local|recovery|quota/i);}});
 await test('malformed storage stays intact until explicit current-Workspace discard',async()=>{const storage=memoryStorage();storage.setItem('studio.collection-recovery/v1/'+W,'{broken');const s=page(storage);s.open();s.input('#collectionName','Visible');await s.submit();assert.equal(s.writes.length,0);assert.equal(storage.getItem('studio.collection-recovery/v1/'+W),'{broken');s.approve(true);s.el('#discardCollectionDraft').onclick();assert.equal(s.el('#collectionName').value,'Visible');assert.equal(s.writes.length,0);assert.match(s.el('#collectionStatus').textContent,/not.*cancel|does not.*cancel/i);});
 await test('closing retains recovery, explicit discard clears local evidence without cancelling',async()=>{const s=page();s.open();s.input('#collectionName','Kept');const waiting=s.submit();s.writes[0].reject(Error('lost'));await waiting;s.approve(true);s.el('#cancelCollection').onclick();const r=page(s.storage);r.open();r.restore();assert.ok(r.run('collectionSession.pending'));r.approve(true);r.el('#discardCollectionDraft').onclick();assert.equal(r.run('collectionSession.pending'),null);assert.equal(r.writes.length,0);assert.equal(r.reads.length,0);assert.match(r.el('#collectionStatus').textContent,/not.*cancel|does not.*cancel/i);});
 await test('changed Workspace refuses retry and inspection of the old session',async()=>{const s=page();s.open();s.input('#collectionName','Kept');const waiting=s.submit();s.writes[0].reject(Error('lost'));await waiting;s.run(`assetState.workspace_id='2'.repeat(32)`);s.approve(true);await s.retry();await s.inspect();assert.equal(s.writes.length,1);assert.equal(s.reads.length,0);assert.ok(s.run('collectionSession.pending'));});
 await test('a delayed inspection cannot unlock a replacement dialog',async()=>{const s=page();s.open();s.input('#collectionName','Kept');const waiting=s.submit(),payload=s.payload(0);s.writes[0].reject(Error('lost'));await waiting;const inspecting=s.inspect();s.el('#collectionDialog').close();s.open(B);s.reads[0].resolve(collectionReceipt(payload,A));await inspecting;assert.equal(s.run('collectionSession.id'),B);assert.equal(s.el('#collectionName').value,'Second');assert.ok(s.run('new StudioCollectionRecovery.Journal(sessionStorage,assetState.workspace_id).get(null).pending'));});
 await test('a deleted collection draft is recoverable without silently recreating it',()=>{const s=page();s.open(A);s.input('#collectionName','Retain deleted');const r=page(s.storage);r.run('assetState.collections=[]');r.el('#recoverCollections').onclick();r.restore();assert.equal(r.el('#collectionName').value,'Retain deleted');assert.equal(r.run('collectionSession.id'),A);assert.equal(r.el('#saveCollection').disabled,true);assert.match(r.el('#collectionComparison').textContent,/missing|deleted/i);assert.equal(r.writes.length,0);});
 await test('tampered receipt bytes preserve the unconfirmed command',async()=>{const s=page();s.open();s.input('#collectionName','Kept');const waiting=s.submit(),reply=collectionReceipt(s.payload(0),A);reply.receipt_sha256='0'.repeat(64);s.writes[0].resolve(reply);await waiting;assert.equal(s.run('collectionSession.id'),null);assert.ok(s.run('collectionSession.pending'));assert.equal(s.el('#saveCollection').disabled,true);});

 await test('discard followed by close does not recreate the local draft',()=>{const s=page();s.open();s.input('#collectionName','Discard me');s.approve(true);s.el('#discardCollectionDraft').onclick();s.el('#cancelCollection').onclick();const r=page(s.storage);r.open();assert.equal(r.el('#restoreCollectionDraft').hidden,true);assert.equal(r.writes.length,0);});
 await test('new input after explicit discard can start a fresh local draft',()=>{const s=page();s.open();s.input('#collectionName','Discard me');s.approve(true);s.el('#discardCollectionDraft').onclick();s.input('#collectionName','New draft');const r=page(s.storage);r.open();r.restore();assert.equal(r.el('#collectionName').value,'New draft');});
 await test('Restore is required before fields can overwrite retained recovery',()=>{const s=page();s.open();s.input('#collectionName','Retained');const r=page(s.storage);r.open();assert.equal(r.el('#collectionName').disabled,true);r.restore();assert.equal(r.el('#collectionName').disabled,false);});
 await test('a whitespace-only edit made after dispatch remains a newer draft',async()=>{const s=page();s.open();s.input('#collectionName','Clicked');const waiting=s.submit();s.input('#collectionName',' Clicked ');s.writes[0].resolve(collectionReceipt(s.payload(0),A));await waiting;assert.equal(s.el('#collectionName').value,' Clicked ');assert.equal(s.run('collectionSession.recovery.draft.values.name'),' Clicked ');});
 await test('unchanged clicked whitespace is normalized only on confirmation',async()=>{const s=page();s.open();s.input('#collectionName',' Clicked ');const waiting=s.submit();s.writes[0].resolve(collectionReceipt(s.payload(0),A));await waiting;assert.equal(s.el('#collectionName').value,'Clicked');assert.equal(s.run('collectionSession.recovery'),null);});
 console.log(JSON.stringify({passed}));
})().catch(e=>{console.error(e);process.exitCode=1;});
