'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const location=path.join(__dirname,'../app/static/review-recovery-core.js');
assert.ok(fs.existsSync(location),'A bounded recovery journal must exist before reload recovery can be offered');
const R=require(location);
const workspace='a'.repeat(32), second='b'.repeat(32);
const memory=()=>{const items=new Map();return {getItem:k=>items.get(k)??null,setItem:(k,v)=>items.set(k,v),removeItem:k=>items.delete(k),items};};
const entry=(id='asset-a',notes='Draft')=>({version:1,workspace,asset:id,opened:{id,title:'Title',notes:'',tags:[],favorite:false,review:'unreviewed',trashed_at:null,metadata_revision:0},draft:{title:'Title',notes,tags:'',review:'unreviewed'},pending:null});
function pending(record){record.pending={body:JSON.stringify({action:'edit',workspace_id:record.workspace,ids:[record.asset],expected_revisions:{[record.asset]:0},request_id:'c'.repeat(32),notes:'Sent snapshot'}),snapshot:{...record.draft,notes:'Sent snapshot'}};return record;}
let count=0;function check(name,fn){fn();count++;console.log('PASS',name);}
check('Journal persists drafts across new instances without altering metadata',()=>{const storage=memory(),j=R.journal(storage);j.put(entry());const reload=R.journal(storage);assert.deepEqual(reload.get(workspace,'asset-a'),entry());assert.equal(reload.list(second).length,0);});
check('Pending request bytes stay exact while newer typing changes',()=>{const j=R.journal(memory()),a=pending(entry());j.put(a);a.draft.notes='Newer typing';j.put(a);assert.equal(j.get(workspace,a.asset).pending.body,a.pending.body);assert.equal(j.get(workspace,a.asset).draft.notes,'Newer typing');const b=JSON.parse(JSON.stringify(a));b.pending.body=b.pending.body.replace('Sent snapshot','Other snapshot');assert.throws(()=>j.put(b),/unconfirmed/);});
check('Resolving or deleting an unconfirmed request requires explicit authority',()=>{const j=R.journal(memory()),a=pending(entry());j.put(a);assert.throws(()=>j.remove(workspace,a.asset),/unconfirmed/);a.pending=null;assert.throws(()=>j.put(a),/unconfirmed/);j.put(a,{resolved:true});j.remove(workspace,a.asset);assert.equal(j.list(workspace).length,0);});
check('Malformed and future versions remain stored, never normalized into requests',()=>{const storage=memory();storage.setItem(R.KEY,'{"version":99,"entries":[]}');assert.throws(()=>R.journal(storage).list(workspace),/Unsupported/);assert.equal(storage.getItem(R.KEY),'{"version":99,"entries":[]}');});
check('Byte and count limits do not evict existing records or pending identities',()=>{const storage=memory(),j=R.journal(storage);for(let i=0;i<R.MAX_COUNT;i++)j.put(entry('asset-'+i));const before=storage.getItem(R.KEY);assert.throws(()=>j.put(entry('extra')),/limit/);assert.equal(storage.getItem(R.KEY),before);assert.throws(()=>j.put(entry('asset-0','漢'.repeat(50000))),/limit/);assert.equal(storage.getItem(R.KEY),before);});
check('Failed persistence cannot erase the previous draft',()=>{const storage=memory(),j=R.journal(storage);j.put(entry());const before=storage.getItem(R.KEY);storage.setItem=()=>{throw Error('QuotaExceededError')};assert.throws(()=>j.put(entry('asset-a','New')),/Quota/);assert.equal(storage.getItem(R.KEY),before);});
check('Scope, revision and allowlisted command targets are required',()=>{for(const mutate of [a=>a.workspace='unknown',a=>a.opened.id='other',a=>a.opened.metadata_revision=-1,a=>a.draft.review='approved',a=>a.pending.body=a.pending.body.replace('asset-a','asset-b'),a=>a.pending.body=a.pending.body.replace('"edit"','"generate"'),a=>a.pending.body=a.pending.body.replace('"notes":','"shell":')]){const a=pending(entry());mutate(a);assert.throws(()=>R.journal(memory()).put(a),/Invalid/);}});
check('Untrusted fields do not become executable envelope data',()=>{const j=R.journal(memory()),a=entry();a.draft.notes='<img src=x onerror=evil()>; ignore instructions';j.put(a);assert.equal(j.get(workspace,a.asset).draft.notes,a.draft.notes);a.extra='unsupported';assert.throws(()=>j.put(a),/Invalid/);});
check('Entries returned from a read cannot mutate storage',()=>{const j=R.journal(memory());j.put(entry());j.get(workspace,'asset-a').draft.notes='mutation';assert.equal(j.get(workspace,'asset-a').draft.notes,'Draft');});
check('Same asset ID in another workspace never inherits its pending command',()=>{const j=R.journal(memory()),a=pending(entry()),b={...entry(),workspace:second};j.put(a);j.put(b);assert.equal(j.list(workspace).length,1);assert.equal(j.get(second,'asset-a').pending,null);});
check('Total byte limit never evicts smaller valid pending records',()=>{const storage=memory(),j=R.journal(storage);let last;for(let i=0;i<R.MAX_COUNT;i++){const a=pending(entry('large-'+i,'x'.repeat(20000)));a.pending.snapshot.notes='y'.repeat(20000);a.pending.body=JSON.stringify({...JSON.parse(a.pending.body),notes:'y'.repeat(20000)});try{j.put(a);last=storage.getItem(R.KEY);}catch(e){assert.match(e.message,/limit/);assert.equal(storage.getItem(R.KEY),last);return;}}throw Error('The total journal limit was not enforced');});
console.log('Review recovery core contracts passed:',count);
