'use strict';const data=JSON.parse(document.getElementById('data').textContent),$=id=>document.getElementById(id);let project=structuredClone(data.project),history=[],ctx=null,nodes=[],timer=null;const buffers={};$('preview').src=data.preview;
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function duration(){return project.shots.reduce((n,s)=>n+s.frames-s.transition_frames,0)*project.fps[1]/project.fps[0];}
function selected(){return project.audio.find(c=>c.id===$('clip').value);}
function form(){const c=selected();if(!c)return;$('gain').value=c.gain_db;$('gainValue').textContent=c.gain_db+' dB';$('start').value=c.start_sample/48000;$('length').value=c.samples/48000;$('fadein').value=c.fade_in/48000;$('fadeout').value=c.fade_out/48000;$('mute').checked=c.mute;}
function draw(){const dur=duration();$('ruler').replaceChildren();for(let i=0;i<=Math.ceil(dur);i++)$('ruler').append(el('span',i+'s'));$('lanes').replaceChildren();let frame=0;const shotlane=el('div',undefined,'lane');for(const s of project.shots){frame-=s.transition_frames;const c=el('div',s.id+(s.transition_frames?' / dissolve':''),'clip');c.style.left=100*frame/(dur*project.fps[0]/project.fps[1])+'%';c.style.width=100*s.frames/(dur*project.fps[0]/project.fps[1])+'%';shotlane.append(c);frame+=s.frames;}$('lanes').append(shotlane);for(const c of project.audio){const lane=el('div',undefined,'lane audio'),clip=el('div',c.bus+' / '+c.gain_db+'dB'+(c.mute?' / muted':''),'clip');clip.style.left=100*c.start_sample/(dur*48000)+'%';clip.style.width=100*c.samples/(dur*48000)+'%';clip.style.opacity=c.mute?'.35':'1';lane.append(clip);$('lanes').append(lane);}$('json').textContent=JSON.stringify(project,null,2);$('undo').disabled=!history.length;form();}
for(const c of project.audio){const opt=el('option',c.id);opt.value=c.id;$('clip').append(opt);}$('clip').addEventListener('change',form);$('gain').addEventListener('input',()=>{$('gainValue').textContent=$('gain').value+' dB';});
function stop(){for(const n of nodes){try{n.stop();}catch{}}nodes=[];clearTimeout(timer);$('status').textContent='Audio stopped.';}
$('apply').addEventListener('click',()=>{const old=selected();if(!old)return;const next={...old,gain_db:Number($('gain').value),mute:$('mute').checked,start_sample:Math.round(Number($('start').value)*48000),samples:Math.round(Number($('length').value)*48000),fade_in:Math.round(Number($('fadein').value)*48000),fade_out:Math.round(Number($('fadeout').value)*48000)};if(!Object.values(next).filter(v=>typeof v==='number').every(Number.isFinite)||next.start_sample<0||next.samples<1||next.start_sample+next.samples>Math.round(duration()*48000)||next.fade_in<0||next.fade_out<0||next.fade_in+next.fade_out>next.samples){$('status').textContent='Invalid timing: clip and fades must fit the project.';return;}stop();history.push(structuredClone(project));Object.assign(old,next);draw();$('stale').textContent='Mix changed. Video preview is stale until re-rendered; audition reflects the new mix.';$('stale').className='warning';$('status').textContent='Edit applied. Source media was not changed.';});
$('undo').addEventListener('click',()=>{if(history.length){stop();project=history.pop();draw();$('status').textContent='Previous project restored.';}});$('stop').addEventListener('click',stop);
$('play').addEventListener('click',async()=>{try{stop();$('preview').pause();ctx??=new AudioContext({sampleRate:48000});await ctx.resume();for(const [id,encoded] of Object.entries(data.audio)){if(!buffers[id]){const bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));buffers[id]=await ctx.decodeAudioData(bytes.buffer);}}const base=ctx.currentTime+.1;for(const c of project.audio){if(c.mute)continue;const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffers[c.asset];if((c.source_sample+c.samples)/48000>source.buffer.duration+.0001)throw Error('Clip exceeds available source');const a=Math.pow(10,(c.gain_db+project.master_gain_db)/20),t=base+c.start_sample/48000,end=t+c.samples/48000;gain.gain.setValueAtTime(c.fade_in?0:a,t);if(c.fade_in)gain.gain.linearRampToValueAtTime(a,t+c.fade_in/48000);if(c.fade_out){gain.gain.setValueAtTime(a,end-c.fade_out/48000);gain.gain.linearRampToValueAtTime(0,end);}source.connect(gain).connect(ctx.destination);source.start(t,c.source_sample/48000,c.samples/48000);nodes.push(source);}$('status').textContent='Auditioning current mix. Audio only; no render or generation submitted.';timer=setTimeout(()=>{$('status').textContent='Audition complete.';},(duration()+.2)*1000);}catch(e){stop();$('status').textContent=String(e);}});
$('export').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='project-edited.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='Project exported. Validate and render it in the accompanying workspace.';});draw();
