"""Emit the checked-in, inert showcase payload as a browser-loadable ES module.

Normal Studio startup needs no build. Run this only after editing the JSON source;
--check verifies the generated file without writing anything.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render(source):
    data = json.loads(source)
    if not isinstance(data, dict) or data.get('version') != 1 or not isinstance(data.get('examples'), dict):
        raise ValueError('Expected version 1 showcase with an examples object')
    # JSON is serialized, never interpolated as source code or HTML.
    return ('// Generated by scripts/build-bundle-showcase.py; edit bundle-showcase.json.\n'
            + 'export default ' + json.dumps(data, indent=2, ensure_ascii=True, allow_nan=False) + ';\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source = ROOT / 'app/static/bundle-showcase.json'
    output = source.with_suffix('.js')
    expected = render(source.read_text(encoding='utf-8'))
    if args.check:
        if not output.is_file() or output.read_text(encoding='utf-8') != expected:
            parser.exit(1, 'Showcase module is stale; run python scripts/build-bundle-showcase.py\n')
        return
    output.write_text(expected, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
